version: "3.9"

services:
  ai-server:
    build: ./ai-server
    container_name: fastapi-ai-server
    ports:
      - "8001:8001" 
    environment:
      - CUDA_VISIBLE_DEVICES=-1  # ✅ TensorFlow GPU 비활성화 (CPU에서 실행)
    volumes:
      - ./ai-server:/app
      - deepface_cache:/root/.deepface/weights  # ✅ DeepFace 캐시 유지
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001  # ✅ 모든 네트워크에서 접근 가능하도록 수정

volumes:
  deepface_cache:  # ✅ DeepFace 캐시 볼륨 추가