places = {
    "airfield": "비행장",
    "airplane cabin": "비행기 객실",
    "airport": "공항",
    "alley": "골목",
    "amphitheater": "원형 극장",
    "amusement arcade": "오락실",
    "amusement park": "놀이공원",
    "aquarium": "수족관",
    "arcade": "아케이드",
    "arena": "경기장",
    "army base": "군사 기지",
    "art gallery": "미술관",
    "assembly line": "조립 라인",
    "athletic field": "운동장",
    "attic": "다락방",
    "auditorium": "강당",
    "badlands": "황무지",
    "bakery": "빵집",
    "ball pit": "볼풀",
    "ballroom": "무도회장",
    "bamboo forest": "대나무 숲",
    "bank vault": "은행 금고",
    "banquet hall": "연회장",
    "bar": "술집",
    "barn": "헛간",
    "barndoor": "헛간 문",
    "baseball field": "야구장",
    "basement": "지하실",
    "basketball court": "농구장",
    "bathroom": "욕실",
    "bazaar": "시장",
    "beach": "해변",
    "beauty salon": "미용실",
    "bedroom": "침실",
    "boardwalk": "산책로",
    "boat deck": "배 갑판",
    "bookstore": "서점",
    "botanical garden": "식물원",
    "bowling alley": "볼링장",
    "boxing ring": "복싱 링",
    "bridge": "다리",
    "bullring": "투우장",
    "bus interior": "버스",
    "bus station": "버스 정류장",
    "butchers shop": "정육점",
    "cabin": "오두막",
    "cafeteria": "구내식당",
    "campsite": "야영장",
    "campus": "캠퍼스",
    "canal": "운하",
    "canyon": "협곡",
    "car interior": "자동차",
    "carrousel": "회전목마",
    "castle": "성",
    "catacomb": "지하 묘지",
    "cemetery": "묘지",
    "chalet": "산장",
    "chemistry lab": "화학 실험실",
    "church": "교회",
    "classroom": "교실",
    "cliff": "절벽",
    "clothing store": "의류 매장",
    "coast": "해안",
    "cockpit": "조종석",
    "coffee shop": "카페",
    "computer room": "컴퓨터실",
    "conference room": "회의실",
    "construction site": "건설 현장",
    "corn field": "옥수수밭",
    "cottage": "시골집",
    "courthouse": "법원",
    "creek": "개울",
    "crosswalk": "횡단보도",
    "department store": "백화점",
    "desert": "사막",
    "restaurant": "식당",
    "dorm room": "기숙사 방",
    "downtown": "도심",
    "dressing room": "탈의실",
    "drugstore": "약국",
    "elevator": "엘리베이터",
    "embassy": "대사관",
    "engine room": "엔진룸",
    "excavation": "발굴지",
    "fabric store": "직물 가게",
    "farm": "농장",
    "fastfood restaurant": "패스트푸드점",
    "cultivated field": "경작지",
    "wild field": "초원",
    "fire station": "소방서",
    "fishpond": "양어장",
    "flea market": "벼룩시장",
    "florist shop": "꽃집",
    "food court": "푸드 코트",
    "football field": "축구장",
    "forest": "숲",
    "garden": "정원",
    "galley": "조리실",
    "garage": "차고",
    "gas station": "주유소",
    "gazebo": "정자",
    "general store": "실내 잡화점",
    "gift shop": "기념품 가게",
    "golf course": "골프장",
    "greenhouse": "온실",
    "grotto": "동굴",
    "gymnasium": "체육관",
    "hangar": "격납고",
    "harbor": "항구",
    "hardware store": "철물점",
    "hayfield": "건초밭",
    "heliport": "헬기 이착륙장",
    "highway": "고속도로",
    "hospital": "병원",
    "hospital room": "병실",
    "hot spring": "온천",
    "hotel": "호텔",
    "icecream parlor": "아이스크림 가게",
    "ice skating rink": "스케이트장",
    "igloo": "이글루",
    "inn": "여관",
    "islet": "섬",
    "jacuzzi": "자쿠지",
    "jail cell": "감방",
    "jewelry shop": "보석 가게",
    "junkyard": "고철 처리장",
    "kennel": "개집",
    "kindergarden": "유치원",
    "kitchen": "주방",
    "lagoon": "석호",
    "lake": "호수",
    "landfill": "쓰레기 매립지",
    "laundromat": "세탁소",
    "lawn": "잔디밭",
    "lecture room": "강의실",
    "legislative chamber": "입법 회의실",
    "library": "도서관",
    "lighthouse": "등대",
    "living room": "거실",
    "loading dock": "하역장",
    "locker room": "탈의실",
    "mansion": "저택",
    "market": "시장",
    "marsh": "습지",
    "martial arts gym": "무술 체육관",
    "moat": "해자",
    "mosque": "모스크",
    "motel": "모텔",
    "mountain": "산",
    "movie theater": "영화관",
    "museum": "박물관",
    "ocean": "바다",
    "office": "사무실",
    "operating room": "수술실",
    "orchard": "과수원",
    "pagoda": "탑",
    "palace": "궁전",
    "pantry": "팬트리",
    "park": "공원",
    "parking lot": "주차장",
    "pasture": "목초지",
    "pharmacy": "약국",
    "phone booth": "전화 부스",
    "laboratory": "연구소",
    "pier": "부두",
    "pizzeria": "피자 가게",
    "playground": "놀이터",
    "playroom": "놀이방",
    "plaza": "광장",
    "pond": "연못",
    "porch": "현관",
    "promenade": "산책로",
    "pub": "펍",
    "racecourse": "경마장",
    "railroad": "철도",
    "rainforest": "열대 우림",
    "recreation room": "오락실",
    "repair shop": "수리점",
    "rice paddy": "논",
    "river": "강",
    "ruin": "유적",
    "runway": "활주로",
    "sandbox": "모래 놀이터",
    "sauna": "사우나",
    "school": "학교",
    "shed": "창고",
    "shopping mall": "쇼핑몰",
    "shower": "샤워실",
    "resort": "리조트",
    "ski slope": "스키 슬로프",
    "sky": "하늘",
    "skyscraper": "고층 건물",
    "slum": "빈민가",
    "snowfield": "설원",
    "soccer field": "축구장",
    "stable": "마구간",
    "baseball stadium": "야구장",
    "football stadium": "미식축구 경기장",
    "soccer stadium": "축구장",
    "stage": "무대",
    "staircase": "계단",
    "street": "거리",
    "subway station": "지하철역",
    "supermarket": "슈퍼마켓",
    "sushi bar": "스시 바",
    "swamp": "늪",
    "swimming pool": "수영장",
    "ticket booth": "매표소",
    "tower": "탑",
    "toyshop": "장난감 가게",
    "train interior": "기차",
    "train station": "기차역",
    "trench": "참호",
    "underwater": "물 속",
    "valley": "계곡",
    "vegetable garden": "채소밭",
    "village": "마을",
    "vineyard": "포도밭",
    "volcano": "화산",
    "volleyball court": "배구장",
    "water park": "워터파크",
    "waterfall": "폭포",
    "wheat field": "밀밭",
    "wind farm": "풍력 발전소",
    "yard": "마당",
    "zoo": "동물원",
    "karaoke room": "노래방",
    "karaoke": "노래방",
    "sea": "바다",
    "concert hall": "콘서트 홀",
    "temple": "사원"
}